cafe/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('menu.urls', namespace='menu')),
    url(r'^order/', include('order.urls', namespace='order')),
    url(r'^statistic/', include('statistic.urls', namespace='statistic')),
]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

order/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'post-order-session',
        views.UpdateBasketItemsInSessionView.as_view(),
        name='post_order_session'),
    url(r'post-order-db', views.PostOrderView.as_view(), name='post_order_db'),
    url(r'^orders$', views.Orders.as_view(), name='orders'),
    url(r'^dayli$', views.OrdersDaily.as_view(), name='orders_daily'),
    url(r'check/(?P<id>\d+)', views.Check.as_view(), name='check'),
    url(r'new/(?P<id>\d+)',
        views.CheckNewOrders.as_view(), name='check_new_orders'),
]

statistic/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'stat', views.Statistic.as_view(), name='stat'),
]

order/models.py
# -*- coding: utf-8 -*
from __future__ import unicode_literals

from django.db import models


class OrderItem(models.Model):
    order = models.ForeignKey('Order')
    food = models.ForeignKey('menu.Food')
    count = models.IntegerField(verbose_name='Количество', default=1)

    class Meta:
        verbose_name = 'Элемент заказа'
        verbose_name_plural = 'Элементы заказа'

    def __unicode__(self):
        return 'Food: {0}, Count: {1}'.format(self.food.name, self.count)


class Order(models.Model):
    time = models.TimeField(
        verbose_name='Время', auto_now_add=True)
    date = models.DateField(
        verbose_name='Дата', auto_now_add=True)
    session = models.CharField(
        verbose_name='Сессия', editable=False, max_length=40, null=True)
    user = models.ForeignKey('auth.User', null=True)

    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

    def __unicode__(self):
        if self.user:
            user = self.user.username
        else:
            user = self.session
        return 'User: {0}, date: {1}, time: {2}'.format(
            user, self.date, self.time)


class Report(models.Model):
    pass

order/views.py
# -*- coding: utf-8 -*
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render
from django.views.generic import View

from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

from menu.models import Food
from .models import Order, OrderItem

import json


class JSONResponseMixin(object):

    def render_to_json_response(self, context, **response_kwargs):
        return JsonResponse(
            self.get_data(context), safe=False,
            **response_kwargs
        )

    def get_data(self, context):
        return context


class UpdateBasketItemsInSessionView(View):

    def post(self, request):
        orderjs = json.loads(request.body)
        request.session['order'] = orderjs

        return HttpResponse(status=200)


class PostOrderView(View):

    def post(self, request):
        orderjs = json.loads(request.body)
        if request.user.is_authenticated():
            order = Order(user=request.user)
        else:
            order = Order(session=request.session.session_key)
        order.save()
        sum_ = 0
        for number, item in orderjs.iteritems():
            food = Food.objects.get(
                name=item['description'], price=item['priceForOne'])
            OrderItem(order=order, food=food, count=item['count']).save()
            sum_ += int(item['price'])
        context = {'order_items': orderjs, 'order_sum': sum_, 'order': order}
        return render(self.request, 'order/check.html', context=context)


class Orders(LoginRequiredMixin, View):
    login_url = '/admin'

    def get(self, request):
        orders = Order.objects.filter(user=self.request.user)
        context_orders = {}
        for i, order in enumerate(orders):
            order_items = order.orderitem_set.all()
            context_orders[i] = {
                'order': order, 'order_items': order_items
            }
        return render(
            self.request,
            'order/orders.html', context={'orders': context_orders}
        )


class OrdersDaily(UserPassesTestMixin, View):
    login_url = '/admin'

    def test_func(self):
        return self.request.user.is_staff

    def get(self, request, *args, **kwargs):
        from datetime import date
        orders = Order.objects.filter(date=date.today())
        context_orders = {}
        orders_sum = 0
        for i, order in enumerate(orders, start=1):
            order_sum = 0
            order_items = order.orderitem_set.all()
            for j, order_item in enumerate(order_items):
                order_sum += order_item.food.price * order_item.count
            orders_sum += order_sum
            context_orders[i] = {
                'order': order, 'order_items': order_items, 'sum': order_sum,
            }
        return render(
            self.request, 'order/orders.html', context={
                'orders': context_orders,
                'orders_sum': orders_sum,
                'orders_count': i,
                'is_daily_orders': True,
            }
        )


class Check(UserPassesTestMixin, View):
    login_url = '/admin'

    def test_func(self):
        return self.request.user.is_staff

    def get(self, request, *args, **kwargs):
        order = Order.objects.get(id=self.kwargs['id'])
        order_items_qs = order.orderitem_set.all()
        order_items = {}
        sum_ = 0
        for i, order_item in enumerate(order_items_qs):
            price = order_item.food.price * order_item.count
            order_items[i] = {
                'description': order_item.food.name,
                'count': order_item.count,
                'priceForOne': order_item.food.price,
                'price': price,
            }
            sum_ += price
        context = {
            'order_items': order_items,
            'order_sum': sum_,
            'order': order,
        }
        return render(self.request, 'order/check.html', context=context)


class CheckNewOrders(JSONResponseMixin, UserPassesTestMixin, View):
    login_url = '/admin'

    def test_func(self):
        return self.request.user.is_staff

    def get(self, request, *args, **kwargs):
        is_new_orders = False
        if Order.objects.filter(id__gt=self.kwargs['id']):
            is_new_orders = True
        context = {
            'is_new_orders': is_new_orders,
            'id_latest': Order.objects.latest('id').id,
        }
        return self.render_to_json_response(context=context)

order/templates/order/check.html
{% extends 'index-base.html' %}
{% load staticfiles %}

{% block title %}
    В гостях у Джангиста
{% endblock %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-8 center-block">
                <h1>Чек заказа</h1>
                <ul>
                    <li>Номер заказа: {{ order.id }}</li>
                    <li>Время: {{ order.time }}</li>
                    <li>Дата: {{ order.date }}</li>
                    <li>Общая стоимость заказа: {{ order_sum }}</li>
                </ul>
                <table class="table">
                    <thead> <tr> <th></th> <th>Наименование</th> <th>Кол-во</th> <th>Цена</th>  <th>Общая цена</th></tr> </thead>
                    <tbody>
                        {% for number, food in order_items.items %}
                            <tr>
                                <th scope="row">{{ forloop.counter }}</th>
                                <td class="calc-description">{{ food.description }}</td>
                                <td>{{ food.count }}</td>
                                <td class="calc-price">{{ food.priceForOne }}</td>
                                <td class="calc-price-sum">{{ food.price }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

order/templates/order/order_inc.html
            <div class="col-md-4 calculator-container">
                <div class="calculator">
                    {% if request.user.is_authenticated %}
                        {% if request.user.is_staff %}
                            <div id="orders-url">
                                <a href="{% url 'order:orders_daily' %}">Заказы текущего дня</a>
                            </div>
                            <div id="orders-url">
                                <a href="{% url 'statistic:stat' %}">Общая статистика</a>
                            </div>
                        {% endif %}
                        <div id="orders-url">
                            <a href="{% url 'order:orders' %}">Мои заказы</a>
                        </div>
                    {% endif %}
                    <table class="table">
                        <thead> <tr> <th></th> <th>Наименование</th> <th>Кол-во</th> <th>Цена</th>  <td></td></tr> </thead>
                        <tbody>
                            <tr hidden>
                                <th scope="row"></th>
                                <td class="calc-description"></td>
                                <td><input type="number" min="1" value="1"></td>
                                <td class="calc-price"></td>
                                <td>&#10006;</td>
                            </tr>
                            {% for number, food in request.session.order.items %}
                                <tr>
                                    <th scope="row">{{ forloop.counter }}</th>
                                    <td class="calc-description">{{ food.description }}</td>
                                    <td><input type="number" min="1" value="{{ food.count }}"></td>
                                    <td class="calc-price" data-price="{{ food.priceForOne }}">{{ food.price }}</td>
                                    <td>&#10006;</td>
                                </tr>
                            {% endfor %}
                            <tr>
                                <th scope="row"></th>
                                <th>Итого</th>
                                <td></td>
                                <th></th>
                            </tr>
                         </tbody>
                    </table>

                    <div class="calc-buttons" >
                        <button id="calc-clear" class='calc-button'>Очистить</button><button id="calc-order" class='calc-button'>Оформить заказ</button>
                    </div>
                </div>
            </div>

order/templates/order/orders.html
{% extends 'index-base.html' %}
{% load staticfiles %}

{% block title %}
    В гостях у Джангиста
{% endblock %}

{% block js %}
    {{ block.super }}
    <script src="{% static 'js/js.cookie.js' %}"></script>
    <script src="{% static 'js/notify.js' %}"></script>
    <script src="{% static 'order/js/check_new_orders.js' %}"></script>
{% endblock %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-8 center-block">
                {% if is_daily_orders %}
                    <h1>Список заказов текущего дня</h1>
                {% else %}
                    <h1>Список заказов</h1>
                {% endif %}
                {% if not orders %}
                    <p>Заказы не найдены!</p>
                {% else %}
                    {% for i, order in orders.items %}
                        <b>Заказ №{{ forloop.counter }}</b>
                        <ul class="order-info">
                            <li data-id="{{ order.order.id }}">Номер заказа: {{ order.order.id }}</li>
                            <li>Время: {{ order.order.time }}</li>
                            {% if not is_daily_orders %}
                                <li>Дата: {{ order.order.date }}</li>
                            {% else %}
                                <li>{{ order.sum }}</li>
                                <li><a href="{% url 'order:check' id=order.order.id %}">Страница чека</a></li>
                            {% endif %}
                        </ul>
                        {% if not is_daily_orders %}
                            <table class="table">
                                <thead> <tr> <th></th> <th>Наименование</th> <th>Кол-во</th> <th>Цена</th>  <th>Общая цена</th></tr> </thead>
                                <tbody>
                                    {% for order_item in order.order_items %}
                                        <tr>
                                            <th scope="row">{{ forloop.counter }}</th>
                                            <td class="calc-description">{{ order_item.food.name }}</td>
                                            <td>{{ order_item.count }}</td>
                                            <td class="calc-price">{{ order_item.food.price }}</td>
                                            <td class="calc-price-sum">{% widthratio order_item.count 1 order_item.food.price %}</td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                            <br>
                        {% endif %}
                    {% endfor %}
                    {% if is_daily_orders %}
                        <p><b>Общая информация:</b></p>
                        <ul>
                            <li>Сумма всех заказов: {{ orders_sum }}</li>
                            <li>Количество заказов: {{ orders_count }}</li>
                        </ul>
                    {% endif %}
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}